### ISSUE TITLE
Add some way to refresh the page on forum view

### ISSUE THREAD

**Issue by ddwo** [worleydl/bg-angular#10]
On android the refresh button in the browser is sort of obnoxious to get to, it'd be nice to have some kind of breadcrumb link/refresh button/pull to refresh solution

**Comment by caseyjmorris** [comment]
On Android Chrome you just drag the page down to refresh though.

**Comment by ddwo** [comment]
yeah that happened since a year ago. i was going to close this but i wasn't sure if apple had pull to refresh

**Comment by ddwo** [comment]
i guess it does
