### ISSUE TITLE
Avatars aren't updating on Lite when they update on full blown BG

### ISSUE THREAD

**Issue by dunkatron** [worleydl/bg-angular#11]
The URL used for my avatar on BG full is http://badgame.net/avs/avatar_60.jpg?m=1421084901, on Lite it's http://badgame.net/avs/avatar_60.jpg. The ?m=xxxx is the cache invalidation value that I assume is update on upload of a new avatar. Looks like a server change is required since the value is missing from the JSON BG Lite receives.

**Comment by worleydl** [comment]
Fixed.
