### ISSUE TITLE
Image-only posts have quote/reply buttons in the wrong position

### ISSUE THREAD

**Issue by zmbps** [worleydl/bg-angular#5]
example:
![](http://a.pomf.se/ildngi.png)

If you toggle the .pull-right float directive then it fixes itself

what it should look like:
![](http://a.pomf.se/porexk.png)

**Comment by worleydl** [comment]
I liked RS's mod that saved space with the buttons but they don't play nice with image only posts.  I updated the image directive so it throws a clear in after the last image in a post so it pushes the buttons down.
