### ISSUE TITLE
Breadcrumb links at the bottom of the page now link back to non-lite

### ISSUE THREAD

**Issue by dunkatron** [worleydl/bg-angular#8]

**Comment by worleydl** [comment]
Cache issue? I wish I knew what was up with that. Maybe an nginx setting I need to change.

**Comment by dunkatron** [comment]
Not sure but that stuff depends on code that translates bg.net links to lite ones, I think. Only have phone to test with at the moment

**Comment by worleydl** [comment]
Ruling this as cache thing, but cache issue should be resolved soon.

**Comment by dunkatron** [comment]
Yeah it works on my phone now. Thanks
