### ISSUE TITLE
Having to click every image to view it is driving me crazy

### ISSUE THREAD

**Issue by dunkatron** [worleydl/bg-angular#9]
I don't end up looking at any images on the board since it takes an extra step. Additionally, the image doesn't automatically open in another tab so when I click the image and hit back my position in the thread is reset.

**Comment by worleydl** [comment]
What's better: Inline loading on click or opening stuff in a new tab?

**Comment by dunkatron** [comment]
Inline, but I'd rather the images just be there. Why don't you want to have that?

**Comment by worleydl** [comment]
There are there unless you ticked the "hide images" checkbox.  At least they should be....

**Comment by dunkatron** [comment]
Fuck. I must have hit that by mistake. Sorry about that.

**Comment by worleydl** [comment]
I still might update the link directive so stuff opens in a newtab if it's not a forum link.
